#!/usr/bin/env bash
# Update package index
apt-get update

# Install nginx
apt-get install -y nginx

chmod o+w /var/www/html

# Configure nginx to serve "Hello World!" at the root
echo "Hello World!" | tee /var/www/html/index.html

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
replacement="servername ;\n\tlocation /redirectme {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "s/server_name ;/$replacement/" /etc/nginx/sites-available/default

# Restart nginx (alternative to systemctl)
service nginx restart

# Check if nginx is running
if pgrep -x "nginx" >/dev/null
then
    echo "Nginx is running."
else
    echo "Nginx failed to start. Check configuration."
fi
