#!/usr/bin/env bash
# a Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
shopt -s extglob
# Iterate through all process directories in /proc
for proc_dir in /proc/[0-9]*/;
do 
    # Extract the process name from cmdline file
    process_name=$(tr '\0' ' ' < "$proc_dir/cmdline")
    if [[ "$process_name" == *bash* ]]; then
        # extract PID from the directory name
        pid=$(basename "$proc_dir")
        echo "$pid $process_name"
    fi
done