#!/usr/bin/env bash
# displays the content of the file /etc/passwd.
# the script only display:
# username
# user id
# Home directory path for the user

while IFS=: read -r username _ uid _  _ home_dir _
do
    echo "$username:$uid:$home_dir"
done < /etc/passwd
