#!/usr/bin/env bash
# tells a the content of story with /etc/passwd:
# username
# group id
# Home directory path for the user

while IFS=: read USERNAME PASSWORD uuid GROUP_ID  GECOS HOME_DIRECTORY SHELL
do
    echo "The user $USERNAME is part of the $GROUP_ID gang,\
    lives in $HOME_DIRECTORY and rides $SHELL.\
    $uuid place is protected by the passcode $PASSWORD,\
    more info about the user here: $GECOS"
done < /etc/passwd
