#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

# resolve docker issue
cp /etc/hosts /etc/hosts.new
sed -i "s/127.0.0.1/127.0.0.2 localhost/" /etc/hosts.new
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
