#!/usr/bin/env bash
# accepts an arguemnt (a username) and runs whoami
# check if arguement is provided
if [ $# -ne 1 ]; then
   echo "Usage: $0 <username>"
exit 1
fi

# Run whoami under the specified user
sudo -u "$1" whoami
