#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user.

# Install Nginx (if not already installed)
if ! command -v nginx &> /dev/null; then
   apt-get update
   apt-get install -y nginx
fi

# configure Nginx to run as nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Listen on all active IPs (0.0.0.0) on port 8080
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart